### ISSUE TITLE
Daemon crash to investigate when "/+{" in topic

### ISSUE THREAD

**Issue by BadWolf42** [BadWolf42/jMQTT#130]
https://community.jeedom.com/t/plus-de-mise-a-jour-de-letat-des-equipements-jmqtt/76605/22

> Bonsoir,
> 
> Bon j’ai trouvé, c’est a cause d’un topic mal formaté sur un équipement BT. J’ai du le créer sans faire attention a ce que je fessait lors des tests avec la passerelle BT.
> Le fait de supprimer ce topic a également réglé le problème de pid qui n’était pas killer lors d’un restart du demon
> 
> Voila a quoi ressemblais mon topic:
> ```
> home/OpenMQTTGateway_ESP32_OLM_GTWW/BTtoMQTT/+{uuid:5308708ee5b543d48190fda69cc0361c}
> ```

I could not reproduce on version 1d275b8
May need more traces and investigation

**Comment by BadWolf42** [comment]
Ok I could not reproduce first because I used topic as an INFO CMD but, as per screen shot from OP, `home/OpenMQTTGateway_ESP32_OLM_GTWW/BTtoMQTT/+{uuid:5308708ee5b543d48190fda69cc0361c}` is the subscription:
https://community.jeedom.com/t/plus-de-mise-a-jour-de-letat-des-equipements-jmqtt/76605/4
![image](https://user-images.githubusercontent.com/8396512/150752821-50229662-82b2-46c9-ae5f-f5422c3c36e1.png)

jMQTT_Daemon log after jMQTT fresh start with bogus subscription:
```
[DEBUG]    : Run         : Received from Jeedom: {"cmd":"subscribeTopic","id":"4","topic":"home\/OpenMQTTGateway_ESP32_OLM_GTWW\/BTtoMQTT\/+{uuid:5308708ee5b543d48190fda69cc0361c}","qos":"1","apikey":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
Traceback (most recent call last):
File "/var/www/html/plugins/jMQTT/resources/jmqttd/jmqttd.py", line 618, in <module>
m.run()
File "/var/www/html/plugins/jMQTT/resources/jmqttd/jmqttd.py", line 447, in run
self.message_map.get(message['cmd'], self.handle_unknown)(message)
File "/var/www/html/plugins/jMQTT/resources/jmqttd/jmqttd.py", line 506, in handle_subscribeTopic
self.jmqttclients[message['id']].mqtt.subscribe_topic(message['topic'], message['qos'])
File "/var/www/html/plugins/jMQTT/resources/jmqttd/jmqttd.py", line 110, in subscribe_topic
res = self.mqttclient.subscribe(topic, qos)
File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1491, in subscribe
raise ValueError('Invalid subscription filter.')
ValueError: Invalid subscription filter.
```

This is happening because ValueError exception is not caught in jmqttd.py `MqttClient.subscribe_topic()`:
https://github.com/Domochip/jMQTT/blob/dd63155b9b9da5a21d2eb6b4ebb622eec3d2849a/resources/jmqttd/jmqttd.py#L109-L115

Same in jmqttd.py `MqttClient.unsubscribe_topic()`
https://github.com/Domochip/jMQTT/blob/dd63155b9b9da5a21d2eb6b4ebb622eec3d2849a/resources/jmqttd/jmqttd.py#L117-L126

paho.mqtt client can raise in `subscribe()` & `unsubscribe()`:
https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L1437

I will create a PR to fix this.
