### ISSUE TITLE
BETA - jMQTT stalled

### ISSUE THREAD

**Issue by BadWolf42** [BadWolf42/jMQTT#75]
May be related to #55

- jMQTT stopped responding around 2021-05-12 02:43:00 (see jMQTT and jMQTT_Local included logfiles)
- Noticed around 2021-05-12 07:05
- Retarted Daemon 2-3 times between 2021-05-12 07:53 and 2021-05-12 08:00
- Got undetailed exception `Id 501 : WebSocket client encountered an Error!` in jMQTT_daemon
- Installed new BETA around 2021-05-12 08:00 and 2021-05-12 08:02
- Did not fix, but I got detailed Exception with new debug logs in jMQTT_daemon:
```
[2021-05-12 08:02:13][ERROR   ] : Id 501 : WebSocket client encountered an Error!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/websocket/_app.py", line 303, in run_forever
    proxy_type=proxy_type)
  File "/usr/local/lib/python3.7/dist-packages/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python3.7/dist-packages/websocket/_handshake.py", line 79, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python3.7/dist-packages/websocket/_handshake.py", line 165, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 413 Request Entity Too Large
```
- Hard killed some process around 2021-05-12 08:05:
```
bad@jeedom:~$ ps auxf |grep jmq
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
bad      19396  0.0  0.0   7348   572 pts/0    S+   08:05   0:00              \_ grep --color=auto jmq
www-data 12663  1.9  2.7  91892 26948 ?        Sl   08:02   0:03 python3 /var/www/html/plugins/jMQTT/resources/jmqttd/jmqttd.py --plugin jMQTT --loglevel warning --socketport 1025 --apikey zzzzzzzzzzzzzzzzzzz --pid /tmp/jeedom/jMQTT/jmqttd.py.pid
www-data 12665  3.5  3.2 212044 32168 ?        S    08:02   0:06 php /var/www/html/plugins/jMQTT/resources/jmqttd/jmqttd.php --plugin jMQTT --socketport 1026 --pid /tmp/jeedom/jMQTT/jmqttd.php.pid
bad@jeedom:~$ sudo kill 12663
bad@jeedom:~$ sudo kill 12665
```
- Up and running since 2021-05-12 08:06:37

Jeedom Backup occurred at 2021-05-12 00:52:03
**Cron day occurred at 2021-05-12 02:36:04 for 270s**

Also got this in http.error, probably not related:
```
[12-May-2021 08:00:28 Europe/Brussels] PHP Fatal error:  Uncaught Error: Undefined class constant 'DEFAULT_PYTHON_PORT' in /var/www/html/plugins/jMQTT/plugin_info/configuration.php:41
Stack trace:
#0 /var/www/html/core/php/utils.inc.php(70): require_once()
#1 /var/www/html/index.php(71): include_file('plugins/jMQTT/p...', 'configuration.p...', 'configuration', 'jMQTT')
#2 {main}
thrown in /var/www/html/plugins/jMQTT/plugin_info/configuration.php on line 41
[12-May-2021 08:05:42 Europe/Brussels] PHP Fatal error:  Uncaught Error: Undefined class constant 'DEFAULT_PYTHON_PORT' in /var/www/html/plugins/jMQTT/plugin_info/configuration.php:41
Stack trace:
#0 /var/www/html/core/php/utils.inc.php(70): require_once()
#1 /var/www/html/index.php(71): include_file('plugins/jMQTT/p...', 'configuration.p...', 'configuration', 'jMQTT')
#2 {main}
thrown in /var/www/html/plugins/jMQTT/plugin_info/configuration.php on line 41
[12-May-2021 08:06:10 Europe/Brussels] PHP Fatal error:  Uncaught Error: Undefined class constant 'DEFAULT_PYTHON_PORT' in /var/www/html/plugins/jMQTT/plugin_info/configuration.php:41
Stack trace:
#0 /var/www/html/core/php/utils.inc.php(70): require_once()
#1 /var/www/html/index.php(71): include_file('plugins/jMQTT/p...', 'configuration.p...', 'configuration', 'jMQTT')
#2 {main}
thrown in /var/www/html/plugins/jMQTT/plugin_info/configuration.php on line 41
```

Included some log files from 2021-05-12 02:40 to 2021-05-12 08:10:00 :
[jMQTT.log](https://github.com/Domochip/jMQTT/files/6464331/jMQTT.log)
[jMQTT_daemon.log](https://github.com/Domochip/jMQTT/files/6464332/jMQTT_daemon.log)
[jMQTT_dep.log](https://github.com/Domochip/jMQTT/files/6464333/jMQTT_dep.log)
[jMQTT_Local.log](https://github.com/Domochip/jMQTT/files/6464334/jMQTT_Local.log)

**Comment by Domochip** [comment]
`Undefined class constant 'DEFAULT_PYTHON_PORT'` error fixed by commit https://github.com/Domochip/jMQTT/commit/868981dc4ea7cd934311ba747d3e4e4849893663

**Comment by Domochip** [comment]
You got some problems about dependancies which has been moved and you have better logging starting 8:00 only.
Need more newer log.
`Handshake status 413 Request Entity Too Large` is very strange...

**Comment by BadWolf42** [comment]
Did not experience this issue with new beta versions and could not reproduce.
I'll re-open if it reoccurs.
Thanks
